### ISSUE TITLE
`ecs-cli --invalid-arg compose service up` exits with exit_code 0

### ISSUE THREAD

**Issue by markriggins** [aws/amazon-ecs-cli#116]
The command `ecs-cli --invalid-arg compose service up`  DIES and gives a USAGE string, but exits with exit code 0, telling the shell that it succeeded.

`ecs-cli --invalid-arg compose service up && echo SUCCESS` will report SUCCESS

and `set -e;  ecs-cli --invalid-arg compose service up; ...` will not exit

**Comment by markriggins** [comment]
ecs-cli version 0.3.0 (2297ef0)

**Comment by uttarasridhar** [comment]
There was a code bug in v0.3.0 release which prevented users from running the cli successfully on ec2 instances with instance metadata. This was fixed in https://github.com/aws/amazon-ecs-cli/pull/115.

Please update to the latest version and reopen this thread if you encounter any issues. Thanks.

**Comment by markriggins** [comment]
This was NOT fixed

$ ./ecs-cli-darwin-amd64-latest --version
ecs-cli version 0.4.6 (3e2a382)

$ ./ecs-cli-darwin-amd64-latest  -X >/dev/null  && echo 'this should not run'
this should not run
