### ISSUE TITLE
Support docker-compose syntax for local "env_file"

### ISSUE THREAD

**Issue by wkonkel** [aws/amazon-ecs-cli#31]
[convert_task_definition.go#L79](https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/compose/ecs/utils/convert_task_definition.go#L79) already has the comment ```// TODO, read env file```

This already works:
```
app:
  environment:
    - A=1
    - B=2
```
But this doesn't:
```
app:
  env_file: ~/.env
```
Where ~/.env contains:
```
A=1
B=2
```
Documentation: [docker-compose.yml reference](https://docs.docker.com/compose/yml/)

**Comment by justinwatkinson** [comment]
+1

**Comment by uttarasridhar** [comment]
This was addressed in the commit f7b182a and released in [v0.3.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.3.0).

You can read the docs [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html) for more information.

**Comment by mehmeta** [comment]
@uttarasridhar this is still not working, please see https://github.com/aws/amazon-ecs-cli/issues/138
