### ISSUE TITLE
Unable to run task definitions on container due to lack of ECR support

### ISSUE THREAD

**Issue by itsmrwave** [aws/amazon-ecs-cli#61]
The latest ECS CLI `v0.1.0 (*cbdc2d5)` creates a cluster with AMIs that doesn't support ECR. The official documentation states, and I quote:

> You can use your Amazon ECR images with Amazon ECS, but you need to satisfy some prerequisites:
> * Your container instances must be using at least version 1.7.0 of the Amazon ECS container agent. The latest version of the Amazon ECS-optimized AMI supports Amazon ECR images in task definitions. For more information, including the latest Amazon ECS-optimized AMI IDs, see Amazon ECS Container Agent Versions.

The AMI currently used for the instance is the Amazon ECS-Optimized Amazon Linux AMI `2015.03.g` which carries `v1.4.0` of the ECS Container Agent. See below ([as per the docs][2]):

| ECS-optimized AMI | ECS Container Agent Version | Docker version | ecs-init version | Supported |
|-----------------|------------------|--------------|-----------|-----|
| 2015.09.c       | 1.7.0            | 1.7.1        | 1.7.0-1   | Yes |
| 2015.09.b       | 1.6.0            | 1.7.1        | 1.6.0-1   | Yes |
| 2015.09.a       | 1.5.0            | 1.7.1        | 1.5.0-1   | Yes |
| 2015.03.g       | 1.4.0            | 1.7.1        | 1.4.0-2   | Yes |

This results in an attribute error when running the task definition on the containers:

```
$ ecs-cli compose --file ecs-compose.yml up
INFO[0001] Using ECS task definition                     TaskDefinition=ecscompose-elk-server:23
INFO[0001] Couldn't run containers                       reason=ATTRIBUTE
```

This problem only exists with images from ECR and not official or namespaces images on Docker Hub.

----

**Sources**

* [Amazon ECR Repositories][1]
* [Amazon ECS-optimized AMI Container Agent Versions][2]

[1]: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_Console_Repositories.html
[2]: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container_agent_versions.html

**Comment by samuelkarp** [comment]
Thanks for reporting.  This was fixed in https://github.com/aws/amazon-ecs-cli/pull/58.  We haven't released new artifacts to download yet, but you can build this locally by following [these instructions](https://github.com/aws/amazon-ecs-cli/blob/cb44924ce8fcc18eeede17d3c48a6260ea546661/README.md#building-the-cli).

**Comment by itsmrwave** [comment]
That was fast. Thanks! :8ball: 

And yes ... looking through the latest commits I can see that there are lots of goodies pending release.

**Comment by itsmrwave** [comment]
@samuelkarp Not sure if I'm doing the wrong thing here with the building (not familiar with Go). I'm hoping you could point me in the right direction.

```
amazon-ecs-cli $ pwd
/Users/Kingori/Repositories/itsmrwave/amazon-ecs-cli

amazon-ecs-cli $ ls -l
total 56
-rw-r--r--   1 Kingori  staff   863 13 Jan 09:46 LICENSE
-rw-r--r--   1 Kingori  staff  2413 13 Jan 09:46 Makefile
-rw-r--r--   1 Kingori  staff   106 13 Jan 09:46 NOTICE
-rw-r--r--   1 Kingori  staff  9821 13 Jan 09:46 README.md
-rw-r--r--   1 Kingori  staff     5 13 Jan 09:46 VERSION
drwxr-xr-x   3 Kingori  staff   102 13 Jan 09:49 bin
drwxr-xr-x   6 Kingori  staff   204 13 Jan 09:54 ecs-cli
drwxr-xr-x  12 Kingori  staff   408 13 Jan 09:46 scripts

amazon-ecs-cli $ make build
. ./scripts/shared_env && ./scripts/build_binary.sh ./bin/local
./scripts/build_binary.sh: line 28: go: command not found
./scripts/build_binary.sh: line 32: go: command not found
make: *** [bin/local/ecs-cli] Error 127
```

I'm on Mac OS X. Do I need to set up any dependencies ... or configure anything?

**Comment by samuelkarp** [comment]
It looks like you don't have the Go compiler installed: https://golang.org/dl/.  You'd need to install that and configure your `GOPATH` properly in order to run `make build`.

However, if you have Docker installed on your Mac, you might be able to just run `make docker-build` and have the build happen inside Docker (rather than installing Go).  I'm not sure whether this will work though as I don't have a Mac and can't test it out myself.

**Comment by abdollar** [comment]
@samuelkarp I ran into the same issue with the error 'reason=ATTRIBUTE' using an ECR based image. Built the binary using a recent master for ecs-cli on a mac - using docker and make docker-build. I can confirm this now works with ECR based images after re-running everything on the new ecs-cli build (*cb44924).

**Comment by uttarasridhar** [comment]
Thanks @abdollar 
The fix is released in [v0.2.0](https://github.com/aws/amazon-ecs-cli/releases/tag/v0.2.0)

**Comment by DorrinPk** [comment]
I still get an error while pulling images from ECR. 

`CannotPullContainerError: Error: image library/nginx-pixel not found`

nginx-pixel is the image in the ECR.  This error is after the task was ran and is in the console. 

Version: `0.4.4`

**Comment by sentientmonkey** [comment]
@DorrinPk For ECR images, you need to provide the full ECR image URI. It should appear like "<account-id>.dkr.ecr.<region>.amazonaws.com/nginx-pixel". You can also fetch this for your image by calling the [DescribeImages API](http://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_DescribeRepositories.html) - it is returned as "repositoryUri". If no domain is set before the image name, Docker assumes that you are pulling from Docker Hub.
